# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Create and configure the Docker container(s)
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.define "dns" do |dns|
		dns.vm.hostname = 'dns'
		dns.vm.box = "ubuntu/trusty32"
		
		dns.vm.network :public_network, :public_network => "eth0"

		dns.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--memory", 512]
			v.customize ["modifyvm", :id, "--name", "dns"]
		end
		
		dns.vm.provision "shell", path: "setup.sh"
	end

	
#	config.vm.define "victim" do |victim|
#		victim.vm.box = "amplifi/ubuntu-desktop-14.04.minimal"
#		victim.vm.hostname = 'victim'
#
#		victim.vm.network :public_network, :public_network => "eth0"
#
#		victim.vm.provider :virtualbox do |v|
#			# v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
#			v.customize ["modifyvm", :id, "--memory", 512]
#			v.customize ["modifyvm", :id, "--name", "victim"]
#		end
#		
#		victim.vm.provision "shell", inline: "ifconfig | grep '192.168'"
#	end
	
end